name: "Publish site"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Build sources 🔧
        run: |
          nix build -j 4
      - name: Generate HTML 🔧
        run: |
          mkdir ./output
          export TARGET=$(pwd)/output
          nix develop -c tailwind-run -o content/tailwind.css 'src/**/*.hs' 
          cd ./content
          ../result/bin/ema-template gen $TARGET
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
